name: Terraform Deployment

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  destroy:
    name: Destroy Terraform Infrastructure
    runs-on: ubuntu-latest
    needs: deploy # Makes sure the destroy job runs after the deploy job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        working-directory: infrastructure/environment/src
        run: terraform init

      - name: Terraform Destroy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        working-directory: infrastructure/environment/src
        run: terraform destroy -auto-approve
        
